A = int(input())
B = int(input())
C = int(input())
multi = str(A*B*C)
print(multi.count('0'))
print(multi.count('1'))
print(multi.count('2'))
print(multi.count('3'))
print(multi.count('4'))
print(multi.count('5'))
print(multi.count('6'))
print(multi.count('7'))
print(multi.count('8'))
print(multi.count('9'))